### ISSUE TITLE
Bug: default value hidden inside fragment

### ISSUE THREAD

**Issue by Kobanister** [DanielMartinus/Stepper-Touch#12]
Hi! @DanielMartinus thanks for the great lib. Can you help me with this bug? Maybe you can fix it or make workaround. Thanks!

<img src="https://user-images.githubusercontent.com/27275100/29161479-0f963e96-7dbf-11e7-86ce-f44d29f9d9ed.png" width="300"/>

**Comment by DanielMartinus** [comment]
Uh oh, that's not good. May I ask which version of the library you're using? And also, is the button put into a fragment, scrollview or anything else that might worth knowing?

**Comment by Kobanister** [comment]
@DanielMartinus I'm using 0.6. Previously i've been using 0.4 and 0.5 there was this bug too.
Yeah, i know, that in previous version stepper had bug with scrollView. This stepper placed in scrollView inside Fragment.

**Comment by DanielMartinus** [comment]
I've tried reproducing it but didn't succeed. Can you share more of your layout structure and how you've styled the Stepper-Touch?

**Comment by Kobanister** [comment]
```
<com.parkingapp.android.utils.views.LockableScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/orderSvLock"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:fillViewport="true"
    android:scrollbars="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:paddingBottom="@dimen/marginPrimary">

 <nl.dionsegijn.steppertouch.StepperTouch
            android:id="@+id/orderStepper"
            android:layout_width="@dimen/_104sdp"
            android:layout_height="@dimen/_40sdp"
            android:layout_gravity="center_horizontal"
            app:stepperBackgroundColor="@color/controlAccent"
            app:stepperButtonColor="@color/backgroundWhite"
            app:stepperTextColor="@color/textBlack" />

 </LinearLayout>
</com.parkingapp.android.utils.views.LockableScrollView>
```

**Comment by DanielMartinus** [comment]
Hi @Kobanister,

A bit of a late reply but today I found some time to look at it again. I've tried a couple of different things. The view hierarchy you posted above, but instead of the LockableScrollView I used a normal scrollview. I've also tested it with a ViewPager and some other ViewGroup elements. But as much as I tried with different UI setups, versions of Android and versions of the AppCompat library unfortunately I didn't encounter the same problem as you have.

So, in order to find the issue it might be best if you upload a demo project with the code somewhere where you can reproduce the same problem. It will help a lot to find a solution.

**Comment by VrasidasP** [comment]
In a similar layout (stepper inside a scrollview inside a pager fragment), I found that in `StepperTouch.kt` - onMeasure, in the line `newHeight = measuredHeight`, measuredHeight is returning as 0.

That could be a clue as to what is going wrong? 

For my project needs I just replaced that line with
`newHeight = if (measuredHeight == 0) newHeight else measuredHeight`

**Comment by kebbbnnn** [comment]
Also encountered this with the latest version. My temporary solution was to call `requestLayout()` after `onGlobalLayout()` is called

```
class StepperLayoutListener implements ViewTreeObserver.OnGlobalLayoutListener {

    private StepperTouch stepperTouch;

    StepperLayoutListener(StepperTouch stepperTouch) {
      this.stepperTouch = stepperTouch;
    }

    @Override
    public void onGlobalLayout() {
      stepperTouch.getViewTreeObserver().removeOnGlobalLayoutListener(this);
      stepperTouch.requestLayout();
    }
  }
```
