### ISSUE TITLE
inside RecyclerView

### ISSUE THREAD

**Issue by ghost** [DanielMartinus/Stepper-Touch#121]
inside a recyclerView the stepper values increase automatically.. please fix it you have one of the best library I know dude! :(

**Comment by DanielMartinus** [comment]
Hi @ghost, thanks for reporting the issue. See the following issue https://github.com/DanielMartinus/Stepper-Touch/issues/42 where the same problem is being reported and discussed. I'll close this issue to prevent any duplicates.
