### ISSUE TITLE
Bug: RTL problem

### ISSUE THREAD

**Issue by nasrabadiAM** [DanielMartinus/Stepper-Touch#20]
**In RTL mode (ie. when device language is rtl like arabic or hebrew,..) ,Text number will be increased when i click on minus, and vice versa.** 

Version Code: 1
Library version: 0.6
Device Language: Persian

### Description:
When Device is in RTL mode (ie. when device language is rtl like arabic or hebrew,..) ,Text number will be increased when i click on minus, and it'll be decreased when i click on plus of stepper touch.

### Steps To Reproduce:
1. Install stepper touch preview app.
2. Change your device language to some RTL languages like arabic or hebrew.
3. Try to increase or decrease stepper touch. 

you can see this behavior in below:

![stepper-touch-rtl-gif](https://user-images.githubusercontent.com/31126059/42450767-7ebd89d2-839a-11e8-8d36-3cc10c4e9294.gif)

**Comment by DanielMartinus** [comment]
Thanks for writing such a detailed issue. It'll be fixed in update `1.0`.
