### ISSUE TITLE
Button not visible

### ISSUE THREAD

**Issue by virajt71** [DanielMartinus/Stepper-Touch#5]
Hi...
I have converted MainActivity.kt file to java file and its working fine in main layout. Its showing me the button in main layout(xml) . But when i am putting it in floating widget file(xml) it does not show me the button. It is only showing me outer border. I tried the commander you have given in the description for colour change of the buttons but it didn't work.

![screenshot_20170427-221532](https://cloud.githubusercontent.com/assets/20619766/25494717/36f2195c-2b98-11e7-895c-0e2a671d5c39.png)

**Comment by DanielMartinus** [comment]
It seems the draw method is not called correctly here to initiate the measurement and thus drawing of the `StepperCounter`. I would need to investigate this.

**Comment by virajt71** [comment]
any luck in solving it??

**Comment by DanielMartinus** [comment]
@virajt71 could you share an example project where this is happening? I'm not able to reproduce. Open a public repo in Github or anything where I can clone the code and try to reproduce it.

**Comment by virajt71** [comment]
Hi....
I have added files to public repo. https://github.com/virajt71/widget

**Comment by DanielMartinus** [comment]
@virajt71 thank you for the sample project. I was able to detect what was going wrong. See #7 for more information. 

To use the new version including a fix for the bug you've reported use the following version:
`compile 'com.github.DanielMartinus:Stepper-Touch:0.4'`

**Comment by virajt71** [comment]
@DanielMartinus  Thank you for fixing the issue.

**Comment by Kobanister** [comment]
@DanielMartinus Hi! I have the same issue even on Stepper-Touch v0.4. But i see this bug in a fragment, not in a minimized view. Thanks!
![screenshot_2017-05-26-09-34-27-263 1](https://cloud.githubusercontent.com/assets/27275100/26483630/a7640dc0-41f6-11e7-9f4b-dd12e97ec9ce.jpeg)

**Comment by DanielMartinus** [comment]
@Kobanister 

1) You are still experiencing the same issue? So you are saying its not fixed?
2) `stepperTouch.enableSideTap(true);` Will be shipped in the next version. It hasn't been tested enough yet. I have to look at the implementation again to see if I think its the correct way to do it. If you want to test out enableSideTap feature you can check out this branch: https://github.com/DanielMartinus/Stepper-Touch/pull/6 and put that in your project
