### ISSUE TITLE
Bug: Changing value when stepper inside scrollview 

### ISSUE THREAD

**Issue by Kobanister** [DanielMartinus/Stepper-Touch#8]
Stepper get stucked when I sliding on them right or left. I think scrollview overrides yout touchEvent.

![screenshot_2017-05-25-13-38-18-896 1](https://cloud.githubusercontent.com/assets/27275100/26447104/ab15215e-414f-11e7-9d46-ce4c12e8bea3.jpeg)

**Comment by Kobanister** [comment]
I've made a workaround with lock the scrollview when stepper is touched. But i wish you'll do the fix :)

**Comment by DanielMartinus** [comment]
Hi @Kobanister thanks for reporting the bug! You're absolutely right. I've directly submitted a PR and closed the issue by disallowing the parent view to intercept touch events of the Stepper Touch widget.
